[2025-01-26T17:08:38.969+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_d_pipeline_compass_reviews.group_ingestion.group_jobs_mongo.MONGO_INGESTION_SANTANDER-WAY scheduled__2025-01-25T06:00:00+00:00 [queued]>
[2025-01-26T17:08:38.998+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_d_pipeline_compass_reviews.group_ingestion.group_jobs_mongo.MONGO_INGESTION_SANTANDER-WAY scheduled__2025-01-25T06:00:00+00:00 [queued]>
[2025-01-26T17:08:38.998+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-01-26T17:08:39.020+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): group_ingestion.group_jobs_mongo.MONGO_INGESTION_SANTANDER-WAY> on 2025-01-25 06:00:00+00:00
[2025-01-26T17:08:39.036+0000] {standard_task_runner.py:57} INFO - Started process 62 to run task
[2025-01-26T17:08:39.040+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_d_pipeline_compass_reviews', 'group_ingestion.group_jobs_mongo.MONGO_INGESTION_SANTANDER-WAY', 'scheduled__2025-01-25T06:00:00+00:00', '--job-id', '329', '--raw', '--subdir', 'DAGS_FOLDER/dag_d_pipeline_compass_reviews.py', '--cfg-path', '/tmp/tmpcc84bg7g']
[2025-01-26T17:08:39.041+0000] {standard_task_runner.py:85} INFO - Job 329: Subtask group_ingestion.group_jobs_mongo.MONGO_INGESTION_SANTANDER-WAY
[2025-01-26T17:08:39.166+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_d_pipeline_compass_reviews.group_ingestion.group_jobs_mongo.MONGO_INGESTION_SANTANDER-WAY scheduled__2025-01-25T06:00:00+00:00 [running]> on host f48abc7117a5
[2025-01-26T17:08:39.338+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='gacarvalho.contato@gmail.com' AIRFLOW_CTX_DAG_OWNER='gacarvalho' AIRFLOW_CTX_DAG_ID='dag_d_pipeline_compass_reviews' AIRFLOW_CTX_TASK_ID='group_ingestion.group_jobs_mongo.MONGO_INGESTION_SANTANDER-WAY' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T06:00:00+00:00'
[2025-01-26T17:09:50.537+0000] {local_task_job_runner.py:294} WARNING - State of this instance has been externally set to success. Terminating instance.
[2025-01-26T17:09:50.540+0000] {process_utils.py:131} INFO - Sending 15 to group 62. PIDs of all processes in the group: [72, 62]
[2025-01-26T17:09:50.540+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 62
[2025-01-26T17:09:50.544+0000] {taskinstance.py:1632} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-26T17:09:50.549+0000] {logging_mixin.py:151} INFO - Erro inesperado: Task received SIGTERM signal
[2025-01-26T17:09:50.549+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=72, status='terminated', started='17:08:39') (72) terminated with exit code None
[2025-01-26T17:09:50.764+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=62, status='terminated', exitcode=0, started='17:08:38') (62) terminated with exit code 0
